name: MegaEssentials
version: '1.0'
main: de.megaessentialsrecode.MegaEssentials
api-version: 1.19
load: STARTUP
softdepend:
  - Vault
author: LevinGamer8
description: just another essentials Plugin
commands:
  admin:
  fly:
  tpa:
  tpahere:
  heal:
  feed:
  navi:
  balance:
  money:
  bank:
  pay:
  eco:
  invsee:
  tpaccept:
  enchant:
  enderchest:
  ec:
  endersee:
  gamemode:
  gm:
  day:
  night:
  sun:
  rain:
  tp:
  tphere:
  spawn:
  setspawn:
  repair:
