name: MegaEssentials
version: '1.0'
main: de.megaessentialsrecode.MegaEssentials
api-version: 1.19
load: STARTUP
depend:
  - Vault
  - PlaceholderAPI
softdepend:
  - LuckPerms
author: LevinGamer8
description: just another essentials Plugin
commands:
  admin:
    permission: megacraft.command.admin
  fly:
    permission: megacraft.command.fly
  tpa:
  tpahere:
  heal:
    permission: megacraft.command.heal
  feed:
    permission: megacraft.command.feed
  navi:
    permission: megacraft.command.navi
  balance:
  balancetop:
  money:
  pay:
  eco:
    permission: megacraft.command.eco
  invsee:
    permission: megacraft.command.invsee
  tpaccept:
  enchant:
    permission: megacraft.command.enchant
  enderchest:
  ec:
  gamemode:
    permission: megacraft.command.gamemode
  gm:
    permission: megacraft.command.gamemode
  day:
    permission: megacraft.command.day
  night:
    permission: megacraft.command.night
  sun:
    permission: megacraft.command.sun
  rain:
    permission: megacraft.command.rain
  tp:
    permission: megacraft.command.teleport
  tphere:
    permission: megacraft.command.tphere
  spawn:
  setspawn:
    permission: megacraft.command.setspawn
  repair:
    permission: megacraft.command.repair
  battlepass:
  player:
    permission: megacraft.command.player
  install:
    permission: megacraft.command.install
  chatclear:
    permission: megacraft.command.chatclear
    aliases: cc
  ping:
  vanish:
    permission: megacraft.command.vanish
    aliases: v
  update:
    permission: megacraft.command.update
